# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: "LeezyData CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      matrix:
        include:
          - xcode: "Xcode_14.3"
            runsOn: firebreak
            name: "macOS 13, Xcode 14.3, Swift 5.8.0"
            destination: "platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro Max"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: xcodebuild test -scheme "LeezyData" -destination "${{ matrix.destination }}" -testPlan "LeezyData" clean test
