# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: slashmo/install-swift@v0.2.1
        with:
          version: 5.8
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_14.0.1.app"
      - name: Build and test ( iOS 16.0)
        run: xcodebuild test -scheme LeezyData -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro Max'
